name: hovernet
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - tqdm
  - pyarrow
  # remove openslide for window because you need to install manually
  # - openslide
  - pip:
    - -r requirements.txt
    - openslide-python
